//
// Created by User on 10/17/2023.
//

#ifndef STUDENTMANAGERSOLUTION_SOLUTIONOBJECTTYPE_H
#define STUDENTMANAGERSOLUTION_SOLUTIONOBJECTTYPE_H

enum SolutionObjectType {
    ADVISOR=0,
    DEGREE=1,
    MODULE=2,
    STUDENT=3,
    COUNT=4
};

#endif //STUDENTMANAGERSOLUTION_SOLUTIONOBJECTTYPE_H
