//
// Created by User on 10/17/2023.
//

#ifndef STUDENTMANAGERSOLUTION_STUDENTADVISOR_H
#define STUDENTMANAGERSOLUTION_STUDENTADVISOR_H


class StudentAdvisor {

};


#endif //STUDENTMANAGERSOLUTION_STUDENTADVISOR_H
